services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2026.2.1
    ports:
      - 127.0.0.1:8123:8123
    volumes:
      - ./.homeassistant:/config
      - ./custom_components:/config/custom_components